### PR TITLE
feat: add first batch of Open edX Filters (backport)

### PR DESCRIPTION
**Pull request by MaferMazu**
## Description

This is a Backport of the [PR #29449](https://github.com/openedx/edx-platform/pull/29449) of the platform: 

* Add PreEnrollmentFilter
* Add PreRegisterFilter
* Add PreLoginFilter

This PR is needed for [FAN-41](https://plataforma-nau.atlassian.net/jira/software/projects/FAN/boards/26?selectedIssue=FAN-41)

### CODE REVIEW

**Review by MoisesGSalas — COMMENTED** [review]
Would you mind fixing the commit message to also include the info about the events you are adding in addition to the filters?

**Comment by MaferMazu** [comment]
Ready @MoisesGSalas , thanks. You can check it here: https://github.com/fccn/edx-platform/pull/1/commits/d0ac31994ed1fc456215e322e249db64d66a7393

**Review by felipemontoya — APPROVED** [review]
This changes are correct and up to date. This PR also adds tests for the new code.
For me this is ready to proceed.

**Comment by felipemontoya** [comment]
Important note: a PR similar to this one will be required for the Maple release as well. For nutmeg this will already be present in the open-release.

**Pull request merged**
